### ISSUE TITLE
执行一段时间就会卡住 貌似是多线程的问题

### ISSUE THREAD

**Issue by xioxin** [lijiejie/GitHack#2]
每次还原100来个文件之后就会卡住
win8.1 64位  Python 2.7.5

**Comment by lijiejie** [comment]
多半是有大的文件一直在下载，并不是卡住。   你可监视下脚本的下载流量。  可能并不是脚本已经卡死了。

**Comment by xioxin** [comment]
我起初也是这么感觉的 我下载了GlassWire来检测流量发现 流量为0

**Comment by xioxin** [comment]
直接执行GitHack.py http://www.openssl.org/.git/ 这个同样出现卡死的现象

**Comment by juiceyang** [comment]
写爬虫的时候遇到了类似问题。
后来发现是因为任务从Queue中取出之后，request失败，而任务也没有再放回Queue。
在except里面把失败的任务放回Queue之后就没有出现过卡死的情况了。
仅提供一些参考。

**Comment by freedomwell** [comment]
> 写爬虫的时候遇到了类似问题。
> 后来发现是因为任务从Queue中取出之后，request失败，而任务也没有再放回Queue。
> 在except里面把失败的任务放回Queue之后就没有出现过卡死的情况了。
> 仅提供一些参考。
  能给出代码吗？？
