### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by r3x5ur** [lijiejie/GitHack#20]
1. 建议增加参数：--threads  修改 `thread_count` 的值（有时候太快了会出被 ban 掉 IP）
2. 建议增加参数：--proxy  一个好工具都有的功能
3. 建议增加参数：--filter [正则表达式|文件前缀/后缀]  过滤一些没用的文件 （比如一些静态文件 assert）

respect~

**Comment by r3x5ur** [comment]
emmm 尝试自动加上一个 /.git

**Comment by lijiejie** [comment]
感谢你提交的建议。 这边更晚一些，会考虑支持你提到的功能参数
