### ISSUE TITLE
403的话是不是就不行？

### ISSUE THREAD

**Issue by jingjinghack** [lijiejie/GitHack#7]
![2017-01-02 14-31-11](https://cloud.githubusercontent.com/assets/16219523/21585287/2112b286-d0f8-11e6-804a-168345812da0.png)

**Comment by lijiejie** [comment]
可先在浏览器试试 /.git/index文件是否能够下载，如果不行，就无法利用

**Comment by jingjinghack** [comment]
不能。
@lijiejie
